### ISSUE TITLE
Add Best Practise Examples around Typescript. 

### ISSUE THREAD

**Issue by Danishkhurshid** [Entermedia-LLC/best-practices#10]
- Simple examples like Why React. Fc is discouraged - See issue (https://github.com/facebook/create-react-app/pull/8177). 
- Why inline the type declaration should not be used.

Better way to infer types: 

// Declaring type of props - see "Typing Component Props" for more examples
`type AppProps = {
  message: string;
};`  // use `interface` if exporting so that consumers can extend 

// Easiest way to declare a Function Component; return type is inferred.
`const App = ({ message }: AppProps) => <div>{message}</div>;`

// you can choose annotate the return type so an error is raised if you accidentally return some other type
`const App = ({ message }: AppProps): JSX.Element => <div>{message}</div>;`

**Comment by bmarshall511** [comment]
@Danishkhurshid Great idea! Got started here: https://entermedia-llc.github.io/best-practices/javascript/typescript/

Feel free to add & create a PR
